### ISSUE TITLE
Need more comment on train_model

### ISSUE THREAD

**Issue by JosephBChoi** [baeklab/PARCtorch#32]
`line 42 - 54` needs more comment. Challenging to understand how loss is computed based on the application. Also, challenging to understand how to update for the new application. 

@JackBeerman Could you please add more comments how the `app` needs to work based on different application?

**Comment by JackBeerman** [comment]
@JosephBChoi  thank you for pointing this out. It was a hotfix that definitely need more comments. This should be addressed now.
